# CognexBarcodeReader - Funding Configuration
# Bu dosya proje için finansal destek seçeneklerini belirler

# GitHub Sponsors
github: alknbugra

# Diğer finansal destek platformları
# Ko-fi: alknbugra
# Patreon: alknbugra
# Open Collective: cognexbarcodereader

# Özel mesaj
message: |
  Bu projeyi beğendiyseniz ve desteklemek istiyorsanız:
  
  - ⭐ GitHub'da yıldız verin
  - 🍴 Projeyi fork edin
  - 🤝 Katkıda bulunun
  - 💬 Geri bildirim verin
  
  Teşekkürler! 🙏
